# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SigV.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import Qt
import pandas as pd
import numpy as np
import pyqtgraph 
from pyqtgraph import PlotWidget , GraphicsLayoutWidget
import time as t
from scipy import signal
import matplotlib.pyplot as plt
import random
from PyQt5.QtGui import QPixmap
from lib.tab import Tabs
from lib.FT import soundfileUtility
from scipy import signal

class newAction(QtWidgets.QAction):
    def __init__(self,parent,iconPath,objectName,keySequance="",method_to_trigger=None):
        super(newAction,self).__init__()
        self.setParent(parent)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(iconPath), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setIcon(icon)
        self.setObjectName(objectName)
        shortCut = QtWidgets.QShortcut(QtGui.QKeySequence(keySequance),parent)
        if method_to_trigger != None : 
            shortCut.activated.connect(method_to_trigger)
            self.triggered.connect(method_to_trigger)

class mainWindow(QtWidgets.QMainWindow) : 
    def __init__(self,parent = None) : 
        super().__init__()
        self.KeyUpMethod = None
        self.KeyDownMethod = None
        self.KeyLeftMethod = None
        self.KeyRightMethod = None
        self.spaceMethod = None
        self.windowResizeMethod = None
    
    def keyPressEvent(self, ev) :
        if ev.key() == Qt.Key_Up : 
            self.KeyUpMethod(ev)
        if ev.key() == Qt.Key_Down :
            self.KeyDownMethod(ev)
        if ev.key() == Qt.Key_Left :
            self.KeyLeftMethod(ev)
        if ev.key() == Qt.Key_Right : 
            self.KeyRightMethod(ev)
        if ev.key() == Qt.Key_Space : 
            self.spaceMethod(ev)
    def resizeEvent(self, ev) : 
        self.windowResizeMethod(ev)

class Ui_SignalViewer(object):

    def __init__(self):
        self.isPaused = False

    def setupUi(self, SignalViewer):
        SignalViewer.setObjectName("SignalViewer")
        SignalViewer.resize(1350, 690)
        SignalViewer.setTabShape(QtWidgets.QTabWidget.Triangular)
        SignalViewer.KeyUpMethod = self.scroll_up
        SignalViewer.KeyDownMethod = self.scroll_down    
        SignalViewer.KeyLeftMethod = self.scroll_left
        SignalViewer.KeyRightMethod = self.scroll_right
        SignalViewer.spaceMethod = self.spaceClicked
        SignalViewer.windowResizeMethod = self.windowResize
        
        self.centralwidget = QtWidgets.QWidget(SignalViewer)
        self.centralwidget.setObjectName("centralwidget")
        SignalViewer.setCentralWidget(self.centralwidget)
        

        self.statusbar = QtWidgets.QStatusBar(SignalViewer)
        self.statusbar.setObjectName("statusbar")
        SignalViewer.setStatusBar(self.statusbar)

        # tool bar
        self.toolBar = QtWidgets.QToolBar(SignalViewer)
        self.toolBar.setObjectName("toolBar")
        SignalViewer.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        # open file
        self.actionnew_file = newAction(SignalViewer, "icons/folder.png", "actionnew_file",method_to_trigger=self.selectFolder)
        # zoom in H
        self.actionzoom_in_h = newAction(SignalViewer, "icons/ic_zoom_in_h_black_24dp.png", "actionzoom_in_h",method_to_trigger=self.zoom_in_h,keySequance="Ctrl+H")
        # zoom out H 
        self.actionzoom_out_h = newAction(SignalViewer, "icons/ic_zoom_out_h_black_24dp.png", "actionzoom_out_h",method_to_trigger=self.zoom_out_h,keySequance="Shift+H")
        # zoom in v 
        self.actionzoom_in_v = newAction(SignalViewer, "icons/ic_zoom_in_v_black_24dp.png", "actionzoom_in_v",method_to_trigger=self.zoom_in_v,keySequance="Ctrl+V")
        # zoom out v 
        self.actionzoom_out_v = newAction(SignalViewer, "icons/ic_zoom_out_v_black_24dp.png", "actionzoom_out_v",method_to_trigger=self.zoom_out_v,keySequance="Shift+V")
        #pause 
        self.actionPause = newAction(SignalViewer, "icons/pause.png", "actionPause",method_to_trigger=self.pause)
        #resume
        self.actionResume = newAction(SignalViewer, "icons/start.png", "actionResume",method_to_trigger=self.resume)
        #save file
        self.actionsave_file = newAction(SignalViewer, "icons/diskette.png", "actionsave_fil",method_to_trigger=self.generateReport)
        # clear
        self.actionClear = newAction(SignalViewer, "icons/delete.png", "actionClear",method_to_trigger=self.clearSignal)

        # change color of spectrogram
        self.labelForComboBox = QtWidgets.QLabel("spectroGram : ")

        # playSound action
        self.playSound = newAction(SignalViewer, "icons/play.png", "playSound",method_to_trigger=self.playSoundFile)

        #colors combo box
        spectrogramsModes = ["viridis","inferno","plasma","palette 4","palette 5"]
        self.colorMode = QtWidgets.QComboBox()
        for mode in spectrogramsModes :
            self.colorMode.addItem(mode)
        self.colorMode.currentTextChanged.connect(self.colorModeChanged)

        # add actions to toolBar
        self.toolbarActions = [self.actionnew_file,self.actionsave_file,self.actionzoom_in_h,self.actionzoom_out_h
                            ,  self.actionzoom_in_v,self.actionzoom_out_v,self.actionPause,self.actionClear,self.playSound] # order is important 
        self.toolBar.addSeparator()
        for action in self.toolbarActions : 
            self.toolBar.addAction(action)
        self.toolBar.addSeparator()
        self.toolBar.addWidget(self.labelForComboBox)
        self.toolBar.addWidget(self.colorMode)
        #disable action
        self.disableWidgets()
        # tab widget 
        self.tabwidget = Tabs()
        self.tabwidget.setParent(self.centralwidget)
        self.tabwidget.resize(SignalViewer.width(), SignalViewer.height())
        self.tabwidget.show()

        self.retranslateUi(SignalViewer)
        QtCore.QMetaObject.connectSlotsByName(SignalViewer)

    def retranslateUi(self, SignalViewer):
        _translate = QtCore.QCoreApplication.translate
        SignalViewer.setWindowTitle(_translate("SignalViewer", "Signal Viewer"))
        self.toolBar.setWindowTitle(_translate("SignalViewer", "toolBar"))
        self.actionnew_file.setText(_translate("SignalViewer", "newfile"))
        self.actionnew_file.setShortcut(_translate("SignalViewer","Ctrl+N"))
        self.actionzoom_in_h.setText(_translate("SignalViewer", "zoom in horizontally"))
        self.actionzoom_in_h.setShortcut(_translate("SignalViewer", "Ctrl+H+Plus"))
        self.actionzoom_out_h.setText(_translate("SignalViewer", "zoom out horizontally"))
        self.actionzoom_out_h.setShortcut(_translate("SignalViewer", "Ctrl+Minus+H"))
        self.actionzoom_in_v.setText(_translate("SignalViewer", "zoom in virtically"))
        self.actionzoom_in_v.setShortcut(_translate("SignalViewer", "Ctrl+Plus+V"))
        self.actionzoom_out_v.setText(_translate("SignalViewer", "zoom out virtically"))
        self.actionzoom_out_v.setShortcut(_translate("SignalViewer", "Ctrl+Minus+V"))
        self.actionPause.setText(_translate("SignalViewer", "Pause"))
        self.actionResume.setText(_translate("SignalViewer", "Resume"))
        self.actionsave_file.setText(_translate("SignalViewer", "save file"))
        self.actionsave_file.setShortcut(_translate("SignalViewer", "Ctrl+S"))
        self.actionClear.setText(_translate("SignalViewer", "Clear a Signal"))
        self.actionClear.setShortcut(_translate("SignalViewer", "Ctrl+D"))
    
    def windowResize(self,event) : 
        self.tabwidget.resize(SignalViewer.width(), SignalViewer.height())
    
    def playSoundFile(self) :
        currentTab = self.tabwidget.currentWidget()
        currentTab.playSound()

    def enableWidgets(self) : 
        for action in self.toolbarActions : 
            action.setEnabled(True)
        self.colorMode.setEnabled(True)
    
    def disableWidgets(self) :
        for action in self.toolbarActions : 
            if action == self.actionnew_file : 
                continue
            action.setEnabled(False)
        self.colorMode.setEnabled(False)

    def spaceClicked(self,ev) :
        if self.isPaused : 
            self.resume()
            self.isPaused = not self.isPaused
        else : 
            self.pause()
            self.isPaused = not self.isPaused

    def clearSignal(self) :
        currentIndex = self.tabwidget.currentIndex()
        self.tabwidget.removeTab(currentIndex)
        if self.tabwidget.count() == 0 : 
            self.disableWidgets()

    def selectFolder(self) :
        dialog = QtWidgets.QFileDialog()
        dialog.setFileMode(QtWidgets.QFileDialog.AnyFile)
        directory = dialog.getOpenFileName(None,'select file','c:\\','csv files (*.csv) ;; sound files (*.wav)')
        fileName = directory[0]
        if fileName == '' :
            self.warnDialog("please Select data files")
            return
            timeData = None
            voltsData = None
        if fileName.split('.')[1] == 'wav' : 
            # sound file
            voltsData,sampling_rate =  soundfileUtility.fn_ReadFile(fileName)
            samplingTime = 1 / sampling_rate
            timeData = [i*samplingTime for i in range(len(voltsData))]
        elif fileName.split('.')[1] == 'csv' :
            # read csv file 
            csvFile1 = pd.read_csv(fileName)
            # exctract data to draw signal 1
            timeData = csvFile1.iloc[:,0]
            voltsData = csvFile1.iloc[:,1]

       
        self.tabwidget.add_new_viewer(timeData, voltsData)
        # self.tabwidget.setCurrentIndex(self.tabwidget.numberOfTabs)
        self.enableWidgets()
        
    def generateReport(self) :
        currentTab = self.tabwidget.currentWidget()
        fig,(subPlot1,subPlot2,subPlot3) = plt.subplots(3)
        fig.suptitle('Data Analysis')
        f, t, Sxx = signal.spectrogram(currentTab.editedVoltsData, int(1 / currentTab.sampleTime))

        subPlot1.plot(currentTab.timeData, currentTab.originalVoltsData, color="rEd")
        # subPlot2.specgram(currentTab.editedVoltsData,int(1 / currentTab.sampleTime))
        subPlot2.pcolormesh(t, f, Sxx, cmap=currentTab.pallete_name)
        subPlot3.plot(currentTab.timeData, currentTab.editedVoltsData, color="magenta")

        subPlot1.title.set_text('signal Before Editing')
        subPlot2.title.set_text('spectogram for the signal after Editing')
        subPlot3.title.set_text('signal after Editing')

        subPlot1.set_xlabel('time (s)')
        subPlot1.set_ylabel('volts (v)')

        subPlot3.set_xlabel('time (v)')
        subPlot3.set_ylabel('volts (v)')

        fig.set_figheight(12)
        fig.set_figwidth(12)

        fig.tight_layout()
        R = list(range(0, 11))
        z = random.choice(R)
        fig.savefig(f"Report_{z}.pdf", bbox_inches='tight')
        window = QtWidgets.QMessageBox()
        window.setWindowTitle("done")
        window.setText("file has been saved as " + str(f"Report_{z}.pdf")+ " in your current directory")
        window.exec_()

    def pause(self) :
        currentTab = self.tabwidget.currentWidget()
        if currentTab.timer.isActive() : 
                currentTab.timer.stop()
                ranges = currentTab.plot.viewRange()
                currentTab.xRangeOfSignal = ranges[0]
                currentTab.yRangeOfSignal = ranges[1]
                   
    def resume(self) : 
        currentTab = self.tabwidget.currentWidget()
        if currentTab.timer.isActive() == False : 
                currentTab.timer.start()
              
    def warnDialog(self,message):
        window = QtWidgets.QMessageBox()
        window.setWindowTitle("error")
        window.setText(message)
        window.exec_()
        
    def zoom_in_h(self) :
        currentTab = self.tabwidget.currentWidget()
        if currentTab.timer.isActive() == False :
            xRangeOfSignal = currentTab.xRangeOfSignal
            currentTab.xRangeStack.append([xRangeOfSignal[0],xRangeOfSignal[1]])
            rangeOfX    = currentTab.xRangeOfSignal
            rangeOfX[0] =  rangeOfX[0] * 0.8
            rangeOfX[1] =  rangeOfX[1] * 0.8
            currentTab.plot.setXRange(rangeOfX[0],rangeOfX[1])
            currentTab.plot1.setXRange(rangeOfX[0],rangeOfX[1])
            currentTab.xRangeOfSignal = [rangeOfX[0],rangeOfX[1]]

    def zoom_out_h(self) :
        currentTab = self.tabwidget.currentWidget()
        if currentTab.timer.isActive() == False :
            xRangeStack = currentTab.xRangeStack
            if len(xRangeStack) != 0 :
                rangeOfX = xRangeStack.pop()
                currentTab.plot.setXRange(rangeOfX[0],rangeOfX[1])
                currentTab.plot1.setXRange(rangeOfX[0],rangeOfX[1])
                currentTab.xRangeOfSignal = [rangeOfX[0],rangeOfX[1]]
    
    def zoom_in_v(self) : 
        currentTab = self.tabwidget.currentWidget()
        if currentTab.timer.isActive() == False :
            yRangeOfSignal = currentTab.yRangeOfSignal
            currentTab.yRangeStack.append([yRangeOfSignal[0],yRangeOfSignal[1]])
            rangeOfY = currentTab.yRangeOfSignal
            rangeOfY[0] =  rangeOfY[0] * 0.8
            rangeOfY[1] =  rangeOfY[1] * 0.8
            currentTab.plot.setYRange(rangeOfY[0],rangeOfY[1])
            currentTab.plot1.setYRange(rangeOfY[0],rangeOfY[1])
            currentTab.yRangeOfSignal = [rangeOfY[0],rangeOfY[1]]

    def zoom_out_v(self) :
        currentTab = self.tabwidget.currentWidget()
        if currentTab.timer.isActive() == False :
            yRangeStack = currentTab.yRangeStack
            if len(yRangeStack) != 0 :
                rangeOfY = yRangeStack.pop()
                currentTab.plot.setYRange(rangeOfY[0],rangeOfY[1])
                currentTab.plot1.setYRange(rangeOfY[0],rangeOfY[1])
                currentTab.yRangeOfSignal = [rangeOfY[0],rangeOfY[1]]
    
    def scroll_up(self,ev) :
        currentTab = self.tabwidget.currentWidget()
        if currentTab.timer.isActive() == False :
            rangOfY = currentTab.yRangeOfSignal
            rangOfY[0] += currentTab.scrollStep_y
            rangOfY[1] += currentTab.scrollStep_y
            currentTab.plot.setYRange(rangOfY[0],rangOfY[1])
            currentTab.plot1.setYRange(rangOfY[0],rangOfY[1])
            currentTab.yRangeOfSignal = [rangOfY[0],rangOfY[1]]
    
    def scroll_down(self,ev) : 
        currentTab = self.tabwidget.currentWidget()
        if currentTab.timer.isActive() == False :
            rangOfY = currentTab.yRangeOfSignal
            rangOfY[0] -= currentTab.scrollStep_y
            rangOfY[1] -= currentTab.scrollStep_y
            currentTab.plot.setYRange(rangOfY[0],rangOfY[1])
            currentTab.plot1.setYRange(rangOfY[0],rangOfY[1])
            currentTab.yRangeOfSignal = [rangOfY[0],rangOfY[1]]

    def scroll_left(self,ev) :
        currentTab = self.tabwidget.currentWidget()
        if currentTab.timer.isActive() == False :
            rangeOfX = currentTab.xRangeOfSignal
            if rangeOfX[0] <= 0 : 
                return
            rangeOfX[0] -= currentTab.scrollStep_x
            rangeOfX[1] -= currentTab.scrollStep_x
            currentTab.plot.setXRange(rangeOfX[0],rangeOfX[1])
            currentTab.plot1.setXRange(rangeOfX[0],rangeOfX[1])
            currentTab.xRangeOfSignal = [rangeOfX[0],rangeOfX[1]]

    def scroll_right(self) :
        currentTab = self.tabwidget.currentWidget()
        if currentTab.timer.isActive() == False :
            rangeOfX = currentTab.xRangeOfSignal
            rangeOfX[0] += currentTab.scrollStep_x
            rangeOfX[1] += currentTab.scrollStep_x
            currentTab.plot.setXRange(rangeOfX[0],rangeOfX[1])
            currentTab.plot1.setXRange(rangeOfX[0],rangeOfX[1])
            currentTab.xRangeOfSignal = [rangeOfX[0],rangeOfX[1]]

    def colorModeChanged(self,mode) : 
        currentTab = self.tabwidget.currentWidget()
        currentTab.SpectrogramViewer.clear()
        if mode == "viridis" :
            currentTab.pallete_name = "viridis"
            currentTab.RGB_Pallete_1 = (0.0, (68, 1, 84, 255))
            currentTab.RGB_Pallete_2 = (0.25, (58, 82, 139, 255))
            currentTab.RGB_Pallete_3 = (0.5, (32, 144, 140, 255))
            currentTab.RGB_palette_4 = (0.75, (94, 201, 97, 255))
            currentTab.RGB_palette_5 = (1.0, (253, 231, 36, 255))
        elif mode == "inferno" :
            currentTab.pallete_name = "inferno"
            currentTab.RGB_Pallete_1 = (1.0, (253, 231, 36, 255))
            currentTab.RGB_Pallete_2 = (0.25, (87, 15, 109, 255))
            currentTab.RGB_Pallete_3 = (0.5, (187, 55, 84, 255))
            currentTab.RGB_palette_4 = (0.75, (249, 142, 8, 255))
            currentTab.RGB_palette_5 = (1.0, (252, 254, 164, 255))
        elif mode == "plasma" :
            currentTab.pallete_name = "plasma"
            currentTab.RGB_Pallete_1 = (0.0, (12, 7, 134, 255))
            currentTab.RGB_Pallete_2 = (0.25, (126, 3, 167, 255))
            currentTab.RGB_Pallete_3 = (0.5, (203, 71, 119, 255))
            currentTab.RGB_palette_4 = (0.75, (248, 149, 64, 255))
            currentTab.RGB_palette_5 = (1.0, (239, 248, 33, 255))

        elif mode == "palette 4" : 
            currentTab.RGB_Pallete_1 = (219, 178, 209, 255)
            currentTab.RGB_Pallete_2 = (147, 71, 66, 255)
            currentTab.RGB_Pallete_3 = (108, 160, 220, 255)
        else : 
            currentTab.RGB_Pallete_1 = (236, 219, 83, 255)
            currentTab.RGB_Pallete_2 = (227, 65, 50, 255)
            currentTab.RGB_Pallete_3 = (219, 178, 209, 255)

        currentTab.drawSpectrogram()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignalViewer = mainWindow()
    ui = Ui_SignalViewer()
    ui.setupUi(SignalViewer)
    SignalViewer.show()
    sys.exit(app.exec_())
